#pragma once

enum class WindowsSystemMessage : unsigned int {
    CLIPBOARD_CLEAR,
    CLIPBOARD_COPY,
    CLIPBOARD_CUT,
    CLIPBOARD_PASTE,
    CLIPBOARD_ASKCBFORMATNAME,
    CLIPBOARD_CHANGECBCHAIN,
    CLIPBOARD_CLIPBOARDUPDATE,
    CLIPBOARD_DESTROYCLIPBOARD,
    CLIPBOARD_DRAWCLIPBOARD,
    CLIPBOARD_HSCROLLCLIPBOARD,
    CLIPBOARD_PAINTCLIPBOARD,
    CLIPBOARD_RENDERALLFORMATS,
    CLIPBOARD_RENDERFORMAT,
    CLIPBOARD_SIZECLIPBOARD,
    CLIPBOARD_VSCROLLCLIPBOARD,
    CURSOR_SETCURSOR,
    KEYBOARD_ACTIVATE,
    KEYBOARD_APPCOMMAND,
    KEYBOARD_CHAR,
    KEYBOARD_DEADCHAR,
    KEYBOARD_HOTKEY,
    KEYBOARD_KEYDOWN,
    KEYBOARD_KEYUP,
    KEYBOARD_KILLFOCUS,
    KEYBOARD_SETFOCUS,
    KEYBOARD_SYSDEADCHAR,
    KEYBOARD_SYSKEYDOWN,
    KEYBOARD_SYSKEYUP,
    KEYBOARD_UNICHAR,
    MOUSE_CAPTURECHANGED,
    MOUSE_LBUTTONDBLCLK,
    MOUSE_LBUTTONDOWN,
    MOUSE_LBUTTONUP,
    MOUSE_MBUTTONDBLCLK,
    MOUSE_MBUTTONDOWN,
    MOUSE_MBUTTONUP,
    MOUSE_MOUSEACTIVATE,
    MOUSE_MOUSEHOVER,
    MOUSE_MOUSEHWHEEL,
    MOUSE_MOUSELEAVE,
    MOUSE_MOUSEMOVE,
    MOUSE_MOUSEWHEEL,
    MOUSE_NCLBUTTONDBLCLK,
    MOUSE_NCLBUTTONDOWN,
    MOUSE_NCLBUTTONUP,
    MOUSE_NCMBUTTONDBLCLK,
    MOUSE_NCMBUTTONDOWN,
    MOUSE_NCMBUTTONUP,
    MOUSE_NCMOUSEHOVER,
    MOUSE_NCMOUSELEAVE,
    MOUSE_NCMOUSEMOVE,
    MOUSE_NCRBUTTONDBLCLK,
    MOUSE_NCRBUTTONDOWN,
    MOUSE_NCRBUTTONUP,
    MOUSE_NCXBUTTONDBLCLK,
    MOUSE_NCXBUTTONDOWN,
    MOUSE_NCXBUTTONUP,
    MOUSE_RBUTTONDBLCLK,
    MOUSE_RBUTTONDOWN,
    MOUSE_RBUTTONUP,
    MOUSE_XBUTTONDBLCLK,
    MOUSE_XBUTTONDOWN,
    MOUSE_XBUTTONUP,
    WINDOW_ACTIVATEAPP,
    WINDOW_CANCELMODE,
    WINDOW_CHILDACTIVATE,
    WINDOW_CLOSE,
    WINDOW_COMPACTING,
    WINDOW_CREATE,
    WINDOW_DESTROY,
    WINDOW_DPICHANGED,
    WINDOW_ENABLE,
    WINDOW_ENTERSIZEMOVE,
    WINDOW_EXITSIZEMOVE,
    WINDOW_GETICON,
    WINDOW_GETMINMAXINFO,
    WINDOW_INPUTLANGCHANGE,
    WINDOW_INPUTLANGCHANGEREQUEST,
    WINDOW_MOVE,
    WINDOW_MOVING,
    WINDOW_NCACTIVATE,
    WINDOW_NCCALCSIZE,
    WINDOW_NCCREATE,
    WINDOW_NCDESTROY,
    WINDOW_NULL,
    WINDOW_QUERYDRAGICON,
    WINDOW_QUERYOPEN,
    WINDOW_QUIT,
    WINDOW_SHOWWINDOW,
    WINDOW_SIZE,
    WINDOW_SIZING,
    WINDOW_STYLECHANGED,
    WINDOW_STYLECHANGING,
    WINDOW_THEMECHANGED,
    WINDOW_USERCHANGED,
    WINDOW_WINDOWPOSCHANGED,
    WINDOW_WINDOWPOSCHANGING,
    MENU_COMMAND,
    MENU_SYSCOMMAND,
    MESSAGE_NOT_SUPPORTED,
};

struct SystemMessage {
    WindowsSystemMessage wmMessageCode;
    unsigned int wParam;
    long lParam;
};

class EngineSubsystem {
public:
	EngineSubsystem();
	virtual ~EngineSubsystem();

    virtual void Initialize();
    virtual void BeginFrame();
    virtual void Update(float deltaSeconds);
    virtual void Render() const;
    virtual void EndFrame();

    virtual bool ProcessSystemMessage(const SystemMessage& msg)=0;

    static WindowsSystemMessage GetWindowsSystemMessageFromUintMessage(unsigned int wmMessage);
protected:
private:
	
};